services:
  web:
    image: nginx:alpine
    environment:
      - DEV_HOST=${DEV_HOST:-local.localhost}
    restart: always
    volumes:
      - ./htdocs:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/templates/default.conf.template:ro
      - ./tls:/usr/share/nginx/tls
      - ./logs:/usr/share/nginx/logs
    ports:
      - 80:80
      - 443:443
  php-fpm:
    build: docker/php-fpm
    environment:
      - DEV_HOST=${DEV_HOST:-local.localhost}
      - APP_ENV=local
    volumes:
      - ./htdocs:/usr/share/nginx/html
